[build]
  base = "frontend/"
  publish = "frontend/build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "22"
  YARN_VERSION = "1.22.22"
  REACT_APP_BACKEND_URL = "https://your-app-name.vercel.app"
  REACT_APP_SOLANA_NETWORK = "mainnet-beta"
  GENERATE_SOURCEMAP = "false"

# API Proxy for development/external backend
[[redirects]]
  from = "/api/*"
  to = "https://your-app-name.vercel.app/api/:splat"
  status = 200
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.devnet.solana.com https://api.mainnet-beta.solana.com wss://api.devnet.solana.com wss://api.mainnet-beta.solana.com;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
